### PR TITLE
Update styled-compenents dependency from v3 to v4

### PR DESCRIPTION
**Pull request by mtendotnet**
Update to `syled-components` v4 to fix issue #35.

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
Thanks for working on this. I suspect yarn.lock also needs to be updated so that Travis will pass.

**Comment by alansouzati** [comment]
to achieve this you can delete `yarn.lock` run `yarn cache clean` and run `yarn install`. this will generate a new yarn.lock file.

The reason for that is because we are using the stable grommet release and yarn does not like that.

For reference:

https://github.com/grommet/grommet-site/blob/master/package.json#L23

and

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

**Comment by alansouzati** [comment]
I will take care of this after merging.

**Comment by mtendotnet** [comment]
Ah ok, noted for next time. Thanks

**Pull request merged**
